---
version: "2"         # required to adjust maintainability checks
checks:
  file-lines:
    config:
      threshold: 400 # Encoders/Decoders are complex...
  method-lines:
    config:
      threshold: 40 # Default of 25 is ridiculous
  return-statements:
    config:
      threshold: 10 # I think they simplify things
engines:
  checkstyle:
    enabled: true
    config: 'checkstyle.xml'
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  pmd:
    enabled: true
    channel: beta
    # ... CONFIG CONTENT ...
    checks:
      AvoidBranchingStatementAsLastInLoop:
        enabled: false
ratings:
  paths:
  - "**.java"
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
  - "stylesheet.css"

